# 千万不要使用tab缩进，否则配置失效
# Site Setting
title: TimoTokki
description:
  This is a demo
owner: TimoTokki
# baseurl: /timotokki.github.io
github_username: TimoTokki

# Build settings
markdown: kramdown
highlighter: rouge
defaults:
  -
    scope:
      path: ""
    values: 
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page